### ISSUE TITLE
Schema bookmarks do not work

### ISSUE THREAD

**Issue by chandermani** [Mermade/shins#21]
Schema bookmarks across actions do not work.

Can be seen in https://mermade.github.io/shins/

Example: Click on `Pet` link. It changes urt to `#schemapet` and nothing changes, but directly clicking `Pet` link in `Schema` section loads it under `#pet`

**Comment by MikeRalphson** [comment]
Thanks for reporting! The problem in shins itself is fixed in v2.1.1-3

Let me know if you're using widdershins, and I will cut a new release which includes a template fix for cases where tags and schemas have the same names.

**Comment by chandermani** [comment]
Hi Mke, Thanks for the quick response. Yes i am using widdershins. So i should update widdershins package?

**Comment by MikeRalphson** [comment]
No problem. Yes shins v2.1.1-3 and widdershins v3.0.2 together should resolve the problem.

**Comment by chandermani** [comment]
Hi Mike, I tried to do take latest package for shins and widdershins, but the problem persists. Shin package was 2.1.1-2 (2.1.1.-3 is  not available). I am attaching my index files.
[index.zip](https://github.com/Mermade/shins/files/1571614/index.zip)

**Comment by MikeRalphson** [comment]
Can you try again? shins 2.1.1-3 (without the extra dot) is definitely published. You should be able to see the fix working on https://mermade.github.io/shins/

**Comment by chandermani** [comment]
Not sure whether i have communicated the issue correctly. If you look at https://mermade.github.io/shins/ and click on the `Pet` schema link in `addPet` the expected behavior is that the document will jump to the `Pet` schema definition. This is not happening.

**Comment by MikeRalphson** [comment]
Thanks for the clarification. This should be fixed in shins v2.1.1-4
